version: "3.8"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=http://localhost #optional

    volumes:
      - /opt/docker-config/jellyfin:/config
      - /mnt/jellyfin/Movies:/movies
      - "/mnt/jellyfin/TV Shows:/tvshows"

    ports:
      - "8096:8096"
      - "8920:8920" #optional
      - #"7359:7359/udp" #optional
      - #"1900:1900/udp" #optional
    restart: unless-stopped

  healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost:8096"]
  interval: 1m
  timeout: 10s
  retries: 3

  deploy:
  resources:
    limits:
      memory: 2g

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8081 #default port is 8080
      - TORRENTING_PORT=6881
    volumes:
      - /opt/docker/config/qbittorrent:/config
      - /mnt/Qbittorrent:/downloads #optional
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped



  

