version: "3.8"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC

    volumes:
      - /opt/docker-config/jellyfin:/config
      - /mnt/jellyfin/Movies:/movies
      - "/mnt/jellyfin/TV Shows:/tvshows"

    ports:
      - "8096:8096"
      - "8920:8920" #optional
      - "7359:7359/udp" #optional
      - "1900:1900/udp" #optional
    restart: unless-stopped
